spring:
  application:
    name: secure-notes
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - read:user
              - user:email
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - profile
              - email
  datasource:
    url: jdbc:postgresql://ep-solitary-leaf-adt2cs1l-pooler.c-2.us-east-1.aws.neon.tech/secure-notes?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_IxPKJ8AbYT9U
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 172800000 # 20 days in milliseconds

frontend:
  url: http://localhost:3000
